### ISSUE TITLE
Fails on start?

### ISSUE THREAD

**Issue by rusenask** [Lightning-AI/LAI-research-template-App#89]
```
[flow] 2022-07-22T13:36:09.122Z AttributeError: module 'lightning.app.frontend' has no attribute 'web'
[flow] 2022-07-22T13:36:09.154Z ERROR: Found an exception when loading your application from app.py. Please, resolve it to run your app.
[flow] 2022-07-22T13:36:09.154Z Traceback (most recent call last):
[flow] 2022-07-22T13:36:09.154Z   File "app.py", line 145, in <module>
[flow] 2022-07-22T13:36:09.154Z     app = L.LightningApp(
[flow] 2022-07-22T13:36:09.154Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/core/app.py", line 102, in __init__
[flow] 2022-07-22T13:36:09.154Z     self._update_layout()
[flow] 2022-07-22T13:36:09.154Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/core/app.py", line 415, in _update_layout
[flow] 2022-07-22T13:36:09.154Z     layout = _collect_layout(self, component)
[flow] 2022-07-22T13:36:09.154Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/layout.py", line 30, in _collect_layout
[flow] 2022-07-22T13:36:09.154Z     layout = flow.configure_layout()
[flow] 2022-07-22T13:36:09.154Z   File "app.py", line 27, in configure_layout
[flow] 2022-07-22T13:36:09.154Z     return frontend.web.StaticWebFrontend(serve_dir=self.serve_dir)
[flow] 2022-07-22T13:36:09.154Z AttributeError: module 'lightning.app.frontend' has no attribute 'web'
[flow] 2022-07-22T13:36:09.247Z INFO: Found dead components ['Flow', 'Server', 'root.notebook_viewer'], Exiting execution!!!
```

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/9080105/180451008-60da0e4c-097f-4c66-ab06-7a09247514c6.png">

version  v.0.0.1

**Comment by Nachimak28** [comment]
I haven't tried doing this on the lightning cloud but this seems to be an error due to an older [code version](https://github.com/Lightning-AI/LAI-research-template-App/commit/caec2243f07b19a9e0db44ae33efd29e585a2815) deployed on the lightning cloud.

I tried doing it locally instead and it works by cloning this repo at its latest state and then running it.

**Comment by aniketmaurya** [comment]
@zippeurfou, we want to update the app gallery with the latest code to avoid this error on clone and run.

**Comment by aniketmaurya** [comment]
Closing this since the SHA is updated, and both `Launch` and `clone & run` buttons are working correctly.
